input {
  heartbeat {
    interval => 5
    message => "ELK Connection Test"
  }
  tcp {
    port => 50000
    codec => json
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "docker-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}